language: node_js
node_js:
  - "stable"
  
cache:
  directories:
    - node_modules

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_KEY  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master